/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Entrar
         * @description Confere a senha e abre a sessao no cookie.
         *
         *     Usuario errado e senha errada devolvem a mesma mensagem de proposito:
         *     quem tenta adivinhar nao descobre qual dos dois acertou.
         */
        post: operations["entrar_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sair
         * @description Apaga o cookie. Sem estado no servidor, nao ha mais o que apagar.
         */
        post: operations["sair_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ler Sessao
         * @description Quem esta logado agora, sem exigir cookie.
         *
         *     E o que a SPA pergunta ao abrir a pagina: um 401 aqui obrigaria a
         *     tela a adivinhar pelo erro de outra consulta.
         */
        get: operations["ler_sessao_api_sessao_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Asns
         * @description Os ASNs com arquivo na pasta, para o seletor da tela.
         *
         *     Esta e a unica rota de dados que nao pede o ?asn=: ela e quem diz
         *     quais existem, e nao ha o que resolver antes dela. O test que varre a
         *     tabela de rotas a dispensa pelo mesmo motivo.
         */
        get: operations["listar_asns_api_asns_get"];
        put?: never;
        /**
         * Criar Asn
         * @description Cria o arquivo de um tenant novo e devolve a lista com ele dentro.
         *
         *     A resposta e a lista inteira, e nao o registro criado: o seletor que
         *     chamou precisa dela de qualquer jeito para desenhar as opcoes, e uma
         *     volta a menos e uma janela a menos com o ASN novo fora da lista.
         *
         *     Nada e gravado antes de as duas conferencias passarem: a de faixa e de
         *     par, do _asn_do_formulario, e a de arquivo ja existente, do criar.
         */
        post: operations["criar_asn_api_asns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plano": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ler Plano
         * @description A rede e as tabelas do plano que o formulario usa para se preencher.
         */
        get: operations["ler_plano_api_plano_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rede": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Gravar Rede
         * @description O namespace das standard do tenant, pelas conferencias do
         *     _asn_do_formulario.
         *
         *     O ASN nao vem do corpo: ele e o nome do arquivo, e quem troca de ASN e
         *     o seletor, criando ou escolhendo outro tenant. Editar o campo para
         *     renomear o arquivo fica para a rodada do rename.
         */
        put: operations["gravar_rede_api_rede_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Peers */
        get: operations["listar_peers_api_peers_get"];
        put?: never;
        /** Criar Peer */
        post: operations["criar_peer_api_peers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/novo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Novo Peer */
        get: operations["novo_peer_api_peers_novo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{ident}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Peer */
        get: operations["ler_peer_api_peers__ident__get"];
        /**
         * Atualizar Peer
         * @description Atualiza o registro do ID da URL.
         *
         *     O ID do corpo e editavel: se o operador o trocou, o registro da URL passa
         *     ao ID novo, e o validar recusa o que ja for de outro peer ou grupo.
         */
        put: operations["atualizar_peer_api_peers__ident__put"];
        post?: never;
        /** Excluir Peer */
        delete: operations["excluir_peer_api_peers__ident__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{ident}/copia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copiar Peer
         * @description O peer inteiro com o proximo ID livre, para abrir como peer novo.
         *
         *     Nao grava nada. O salvar recusa o que a copia repetir (token, IP remoto,
         *     prefixo de downstream) e aponta o campo, e o operador corrige ali.
         */
        get: operations["copiar_peer_api_peers__ident__copia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previa Peer
         * @description Valida e monta os blocos do formulario sem gravar nada.
         *
         *     O `id` e o do registro que a tela esta editando, e falta no peer novo. O
         *     erro de validacao volta em 200 e sem bloco. A remocao fica de fora: ela
         *     desfaz o que esta no equipamento, e o que esta no equipamento e o registro
         *     salvo, que o GET /api/peers/{ident}/saida devolve.
         */
        post: operations["previa_peer_api_peers_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{ident}/saida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saida Peer */
        get: operations["saida_peer_api_peers__ident__saida_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/irr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar Irr
         * @description Os prefixos do ASN no IRR, pelo bgpq4, sem gravar nada.
         *
         *     A consulta precisa so do ASN e do apelido: o resultado vai para os campos
         *     de prefixo da tela, que o operador ainda edita antes de salvar. O ASN e o
         *     do peer consultado, e nao o do tenant, entao o `t` nao e lido: ele existe
         *     porque a varredura das rotas cobra o ?asn= de toda rota de dados, e uma
         *     consulta de IRR nao e excecao para quem esta numa rede.
         */
        post: operations["consultar_irr_api_irr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Grupos */
        get: operations["listar_grupos_api_grupos_get"];
        put?: never;
        /** Criar Grupo */
        post: operations["criar_grupo_api_grupos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/novo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Novo Grupo */
        get: operations["novo_grupo_api_grupos_novo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/{ident}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Grupo */
        get: operations["ler_grupo_api_grupos__ident__get"];
        /** Atualizar Grupo */
        put: operations["atualizar_grupo_api_grupos__ident__put"];
        post?: never;
        /** Excluir Grupo */
        delete: operations["excluir_grupo_api_grupos__ident__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/{ident}/copia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copiar Grupo
         * @description O grupo inteiro com o proximo ID livre. O nome repetido e o que o
         *     salvar recusa. A copia nasce sem membro: os peers seguem no original.
         */
        get: operations["copiar_grupo_api_grupos__ident__copia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previa Grupo
         * @description A previa do grupo, com o mesmo contrato da do peer.
         */
        post: operations["previa_grupo_api_grupos_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/{ident}/saida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saida Grupo */
        get: operations["saida_grupo_api_grupos__ident__saida_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Blocos */
        get: operations["ler_blocos_api_blocos_get"];
        /** Salvar Blocos */
        put: operations["salvar_blocos_api_blocos_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocos/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previa Blocos
         * @description O bloco de originacao que o salvar escreveria, sem gravar nada.
         */
        post: operations["previa_blocos_api_blocos_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocos/irr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar Blocos
         * @description Consulta o IRR do AS da rede e mescla com o texto recebido.
         *
         *     A base da mesclagem e o texto que veio, e nao o arquivo: o operador pode
         *     ter mexido numa linha antes de consultar. O prefixo torto e recusado antes
         *     da consulta, nomeado no campo dele. Nada e gravado.
         */
        post: operations["consultar_blocos_api_blocos_irr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ler Config
         * @description A config inteira numa resposta so, montada na hora pelo render.
         *
         *     E a leitura por registro, na ordem de colagem: cada secao e o bloco de um
         *     peer, de um grupo ou dos prefixos proprios, inteiro e colavel sozinho.
         */
        get: operations["ler_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/organizada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ler Config Organizada
         * @description A config inteira por tipo de objeto, para o arquivo do "baixar tudo".
         *
         *     E a mesma montagem do /config, reagrupada: os sets, os route-filters, as
         *     estaticas e um `bgp` so com todas as sessoes. A tela continua lendo o
         *     /config - o que sai daqui e o arquivo que se cola de uma vez.
         */
        get: operations["ler_config_organizada_api_config_organizada_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/base.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Baixar Base */
        get: operations["baixar_base_base_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politica-cliente.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Politica Do Cliente
         * @description O documento que o ISP entrega ao cliente, em PDF.
         *
         *     Fora de /api pelo mesmo motivo do /base.txt: nao e um dado do cadastro,
         *     e um arquivo montado na hora do download. A data sai daqui e nao do
         *     politica.py, que fica sem relogio e por isso testavel.
         *
         *     O cadastro entra junto com a Rede porque a tabela do alias publica o
         *     identificador dos upstreams, que so existe no arquivo do tenant. Os
         *     grupos vao junto porque o upstream agrupado nao emite 5PPA proprio: o
         *     identificador que vale e o do grupo.
         */
        get: operations["politica_do_cliente_politica_cliente_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raiz
         * @description A raiz leva para a lista da SPA.
         *
         *     O 307 e temporario de proposito: um 308 ficaria no cache do navegador do
         *     operador, e voltar atras viraria limpeza de cache. Quem segue o redirect
         *     sem pensar e o HEALTHCHECK do Dockerfile, que bate em / desde antes deste
         *     corte e continua lendo 200 no fim da corrente (o /peers servido pelo build).
         */
        get: operations["raiz__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AsnPedido
         * @description O par do formulario de um tenant novo.
         *
         *     Os dois campos sao texto, como os do resto do app: quem converte e o
         *     _asn_do_formulario, que devolve o erro no campo que o causou. O par
         *     inteiro vem junto porque um ASN de 32 bits precisa do namespace para
         *     ter um arquivo que funcione: sem ele, o tenant nasceria estourando na
         *     primeira leitura e a tela nao teria como conserta-lo, porque o plano
         *     do tenant e justamente o que falha.
         */
        AsnPedido: {
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Politica
             * @default
             */
            politica: string;
        };
        /** Aviso */
        Aviso: {
            /** Campo */
            campo: string;
            /** Mensagem */
            mensagem: string;
        };
        /** Blocos */
        Blocos: {
            texto: components["schemas"]["BlocosTexto"];
            /** Originacao */
            originacao?: string | null;
            /** Remover */
            remover?: string | null;
        };
        /** BlocosIrrPedido */
        BlocosIrrPedido: {
            /**
             * V4
             * @default
             */
            v4: string;
            /**
             * V6
             * @default
             */
            v6: string;
            /**
             * Forcar
             * @default false
             */
            forcar: boolean;
        };
        /**
         * BlocosTexto
         * @description O texto dos dois editores, no formato da textarea de hoje.
         *
         *     Uma linha por prefixo: o CIDR e depois as communities. Linha comecada por
         *     `!-` e prefixo fora de servico, e o `!-` no fim da linha e a marca do que
         *     sumiu da consulta ao IRR, que o salvar ignora.
         */
        BlocosTexto: {
            /**
             * V4
             * @default
             */
            v4: string;
            /**
             * V6
             * @default
             */
            v6: string;
        };
        /**
         * Config
         * @description Toda a config numa resposta so, na ordem em que se cola.
         */
        Config: {
            /** Secoes */
            secoes: components["schemas"]["SecaoConfig"][];
        };
        /**
         * ErroResposta
         * @description O corpo de toda recusa da API: um erro por campo e os avisos.
         */
        ErroResposta: {
            /** Erros */
            erros: {
                [key: string]: string;
            };
            /**
             * Avisos
             * @default []
             */
            avisos: components["schemas"]["Aviso"][];
        };
        /** GrupoForm */
        GrupoForm: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Nome
             * @default
             */
            nome: string;
            /**
             * Tipo
             * @default parceiro
             */
            tipo: string;
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Classe
             * @default
             */
            classe: string;
            /**
             * Lp Base
             * @default
             */
            lp_base: string;
            /**
             * Origem
             * @default
             */
            origem: string;
            /**
             * Pop
             * @default
             */
            pop: string;
            /**
             * Aprendizado
             * @default
             */
            aprendizado: string;
            /**
             * Aprendizado Ix
             * @default
             */
            aprendizado_ix: string;
            /**
             * Ix Id
             * @default
             */
            ix_id: string;
            /**
             * Prepend Base
             * @default
             */
            prepend_base: string;
            /**
             * Timer Keepalive
             * @default
             */
            timer_keepalive: string;
            /**
             * Timer Hold
             * @default
             */
            timer_hold: string;
            /**
             * Bfd
             * @default true
             */
            bfd: boolean;
            /**
             * Graceful Restart
             * @default true
             */
            graceful_restart: boolean;
            /**
             * Default Route
             * @default false
             */
            default_route: boolean;
            /**
             * Bh Upstream
             * @default
             */
            bh_upstream: string;
            /**
             * Prefixos V4
             * @default []
             */
            prefixos_v4: string[];
            /**
             * Prefixos V6
             * @default []
             */
            prefixos_v6: string[];
            /**
             * Te Prefixos V4
             * @default []
             */
            te_prefixos_v4: string[];
            /**
             * Te Prefixos V6
             * @default []
             */
            te_prefixos_v6: string[];
            /**
             * Ap Block
             * @default []
             */
            ap_block: string[];
            /**
             * Ap Te
             * @default []
             */
            ap_te: string[];
            /**
             * Ap Allowed
             * @default []
             */
            ap_allowed: string[];
            /**
             * Ap Prefer
             * @default []
             */
            ap_prefer: string[];
            /**
             * Communities
             * @default []
             */
            communities: string[];
            /**
             * Large Communities
             * @default []
             */
            large_communities: string[];
        };
        /** GrupoRegistro */
        GrupoRegistro: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            formulario: components["schemas"]["GrupoForm"];
            /** Membros */
            membros: components["schemas"]["Membro"][];
        };
        /** GrupoResumo */
        GrupoResumo: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            /** Tipo */
            tipo: string;
            /** Membros */
            membros: number;
        };
        /** GrupoSalvo */
        GrupoSalvo: {
            registro: components["schemas"]["GrupoRegistro"];
            /** Arquivo */
            arquivo: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IrrPedido */
        IrrPedido: {
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Apelido
             * @default
             */
            apelido: string;
            /**
             * Forcar
             * @default false
             */
            forcar: boolean;
        };
        /**
         * LoginPedido
         * @description Usuario e senha do POST /api/login.
         *
         *     Modelo com o extra="forbid" do resto: um nome de campo trocado no
         *     front nao pode passar em silencio e virar um login vazio.
         */
        LoginPedido: {
            /**
             * Usuario
             * @default
             */
            usuario: string;
            /**
             * Senha
             * @default
             */
            senha: string;
        };
        /** Membro */
        Membro: {
            /** Id */
            id: number;
            /** Token */
            token: string;
        };
        /**
         * Padroes
         * @description O _padroes() do formulario.py: o que a cascata de defaults le.
         */
        Padroes: {
            /** Tipos */
            tipos: {
                [key: string]: components["schemas"]["TabelaTipo"];
            };
            /** Origem Tipo */
            origem_tipo: {
                [key: string]: number;
            };
            /** Origem Classe */
            origem_classe: {
                [key: string]: number;
            };
            /** Downstream */
            downstream: string[];
            /** Origens Por Tipo */
            origens_por_tipo: {
                [key: string]: number[];
            };
            /** Origem Nome */
            origem_nome: {
                [key: string]: string;
            };
        };
        /** PeerForm */
        PeerForm: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Apelido
             * @default
             */
            apelido: string;
            /**
             * Nome
             * @default
             */
            nome: string;
            /**
             * Tipo
             * @default cliente
             */
            tipo: string;
            /**
             * Grupo Id
             * @default
             */
            grupo_id: string;
            /**
             * Politica De
             * @default
             */
            politica_de: string;
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Descricao
             * @default
             */
            descricao: string;
            /**
             * Classe
             * @default
             */
            classe: string;
            /**
             * Lp Base
             * @default
             */
            lp_base: string;
            /**
             * Origem
             * @default
             */
            origem: string;
            /**
             * Pop
             * @default
             */
            pop: string;
            /**
             * Aprendizado
             * @default
             */
            aprendizado: string;
            /**
             * Ix Id
             * @default
             */
            ix_id: string;
            /**
             * Route Limit
             * @default
             */
            route_limit: string;
            /**
             * Prepend Base
             * @default
             */
            prepend_base: string;
            /**
             * Timer Keepalive
             * @default
             */
            timer_keepalive: string;
            /**
             * Timer Hold
             * @default
             */
            timer_hold: string;
            /**
             * Bfd
             * @default true
             */
            bfd: boolean;
            /**
             * Graceful Restart
             * @default true
             */
            graceful_restart: boolean;
            /**
             * Default Route
             * @default false
             */
            default_route: boolean;
            /**
             * Bh Upstream
             * @default
             */
            bh_upstream: string;
            /**
             * Prefixos V4
             * @default []
             */
            prefixos_v4: string[];
            /**
             * Prefixos V6
             * @default []
             */
            prefixos_v6: string[];
            /**
             * Te Prefixos V4
             * @default []
             */
            te_prefixos_v4: string[];
            /**
             * Te Prefixos V6
             * @default []
             */
            te_prefixos_v6: string[];
            /**
             * Ap Block
             * @default []
             */
            ap_block: string[];
            /**
             * Ap Te
             * @default []
             */
            ap_te: string[];
            /**
             * Ap Allowed
             * @default []
             */
            ap_allowed: string[];
            /**
             * Ap Prefer
             * @default []
             */
            ap_prefer: string[];
            /**
             * Communities
             * @default []
             */
            communities: string[];
            /**
             * Large Communities
             * @default []
             */
            large_communities: string[];
            /**
             * Sessao V4 Local
             * @default
             */
            sessao_v4_local: string;
            /**
             * Sessao V4 Remoto
             * @default
             */
            sessao_v4_remoto: string;
            /**
             * Sessao V6 Local
             * @default
             */
            sessao_v6_local: string;
            /**
             * Sessao V6 Remoto
             * @default
             */
            sessao_v6_remoto: string;
        };
        /** PeerRegistro */
        PeerRegistro: {
            /** Id */
            id: number;
            /** Token */
            token: string;
            formulario: components["schemas"]["PeerForm"];
        };
        /**
         * PeerResumo
         * @description Uma linha da barra lateral e da paleta de comandos.
         */
        PeerResumo: {
            /** Id */
            id: number;
            /** Token */
            token: string;
            /** Tipo */
            tipo: string;
            /** Asn */
            asn: number;
            /** Apelido */
            apelido: string;
            /** Nome */
            nome: string;
            /** Grupo Id */
            grupo_id: number | null;
            /** Politica De */
            politica_de?: number | null;
        };
        /** PeerSalvo */
        PeerSalvo: {
            registro: components["schemas"]["PeerRegistro"];
            /** Arquivo */
            arquivo: string;
            /**
             * Avisos
             * @default []
             */
            avisos: components["schemas"]["Aviso"][];
        };
        /** Plano */
        Plano: {
            rede: components["schemas"]["RedeAtual"];
            padroes: components["schemas"]["Padroes"];
            /** Tipos */
            tipos: string[];
            /** Tipos Com Criar Lista */
            tipos_com_criar_lista: string[];
            /** Classes Cliente */
            classes_cliente: string[];
            /** Lp Base */
            lp_base: {
                [key: string]: number;
            };
            /** Route Limit */
            route_limit: {
                [key: string]: number;
            };
            /** Route Limit Exemplo */
            route_limit_exemplo: {
                [key: string]: number;
            };
            /** Prepend Max */
            prepend_max: number;
            /** Prepend Implementado */
            prepend_implementado: number;
            /** Pop Min */
            pop_min: number;
            /** Pop Max */
            pop_max: number;
            /** Aprendizado Min */
            aprendizado_min: number;
            /** Aprendizado Max */
            aprendizado_max: number;
            /** Pop Usados */
            pop_usados: number[];
            /** Aprendizado Usados */
            aprendizado_usados: number[];
            /** Campos Por Tipo */
            campos_por_tipo: {
                [key: string]: string[];
            };
            /** Campos Por Tipo Grupo */
            campos_por_tipo_grupo: {
                [key: string]: string[];
            };
            sugestoes: components["schemas"]["Sugestoes"];
        };
        /** Prefixos */
        Prefixos: {
            /** V4 */
            v4: string[];
            /** V6 */
            v6: string[];
        };
        /**
         * Previa
         * @description O que o salvar escreveria, sem gravar nada.
         *
         *     Com erro de validacao, `erros` vem cheio e os blocos vem nulos: a tela nao
         *     pode ter o que copiar de um registro que o salvar recusaria. `salvo` e o
         *     arquivo atual em out/, para o diff, ou nulo quando nao ha.
         */
        Previa: {
            /**
             * Erros
             * @default {}
             */
            erros: {
                [key: string]: string;
            };
            /**
             * Avisos
             * @default []
             */
            avisos: components["schemas"]["Aviso"][];
            /** Bloco */
            bloco?: string | null;
            /** Criar Lista */
            criar_lista?: string | null;
            /** Arquivo */
            arquivo?: string | null;
            /** Salvo */
            salvo?: string | null;
        };
        /** RedeAtual */
        RedeAtual: {
            /** Asn */
            asn: string;
            /** Politica */
            politica: string;
        };
        /** RedeForm */
        RedeForm: {
            /**
             * Politica
             * @default
             */
            politica: string;
        };
        /**
         * Saida
         * @description Os blocos do registro salvo, que e o que esta no equipamento.
         */
        Saida: {
            /** Bloco */
            bloco: string;
            /** Remover */
            remover?: string | null;
            /** Criar Lista */
            criar_lista?: string | null;
            /** Arquivo */
            arquivo: string;
        };
        /**
         * SecaoConfig
         * @description Um pedaco da config inteira, ja renderizado.
         *
         *     `arquivo` e o nome em out/ que aquele bloco grava, e `salvo` diz se ele
         *     esta la. Os dois sao nulos no base, que e montado a cada requisicao pelo
         *     render e nunca teve arquivo proprio.
         */
        SecaoConfig: {
            /** Chave */
            chave: string;
            /** Titulo */
            titulo: string;
            /** Texto */
            texto: string;
            /** Arquivo */
            arquivo?: string | null;
            /** Salvo */
            salvo?: boolean | null;
        };
        /**
         * SessaoResposta
         * @description Quem esta logado. E a resposta do login, do logout e do /sessao.
         */
        SessaoResposta: {
            /** Logado */
            logado: boolean;
            /** Usuario */
            usuario?: string | null;
        };
        /**
         * Sugestao
         * @description Uma community que o formulario oferece para o operador clicar.
         *
         *     O `valor` e o que entra no campo, o `rotulo` e o que a busca do
         *     operador casa e le, e o `grupo` e o cabecalho da lista.
         */
        Sugestao: {
            /** Valor */
            valor: string;
            /** Rotulo */
            rotulo: string;
            /** Grupo */
            grupo: string;
        };
        /**
         * Sugestoes
         * @description Uma lista por campo: a standard e a large nao cabem na mesma.
         *
         *     Os dois campos do formulario tem formas diferentes (`ASN:VALOR` e
         *     `ASN:V1:V2`), e a validacao recusa a trocada: juntar as duas listas
         *     seria oferecer o erro.
         */
        Sugestoes: {
            /** Communities */
            communities: components["schemas"]["Sugestao"][];
            /** Large Communities */
            large_communities: components["schemas"]["Sugestao"][];
        };
        /** TabelaTipo */
        TabelaTipo: {
            /** Lp Base */
            lp_base: number | null;
            /** Route Limit */
            route_limit: number | null;
            /** Timer Keepalive */
            timer_keepalive: number | null;
            /** Timer Hold */
            timer_hold: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    entrar_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPedido"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    sair_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_sessao_api_sessao_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    listar_asns_api_asns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    criar_asn_api_asns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsnPedido"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_plano_api_plano_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plano"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    gravar_rede_api_rede_put: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeAtual"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    listar_peers_api_peers_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerResumo"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    criar_peer_api_peers_post: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerSalvo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    novo_peer_api_peers_novo_get: {
        parameters: {
            query: {
                tipo?: string;
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRegistro"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_peer_api_peers__ident__get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRegistro"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    atualizar_peer_api_peers__ident__put: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerSalvo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    excluir_peer_api_peers__ident__delete: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    copiar_peer_api_peers__ident__copia_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRegistro"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    previa_peer_api_peers_previa_post: {
        parameters: {
            query: {
                id?: number | null;
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Previa"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    saida_peer_api_peers__ident__saida_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saida"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    consultar_irr_api_irr_post: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IrrPedido"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prefixos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    listar_grupos_api_grupos_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoResumo"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    criar_grupo_api_grupos_post: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoSalvo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    novo_grupo_api_grupos_novo_get: {
        parameters: {
            query: {
                tipo?: string;
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoRegistro"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_grupo_api_grupos__ident__get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoRegistro"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    atualizar_grupo_api_grupos__ident__put: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoSalvo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    excluir_grupo_api_grupos__ident__delete: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    copiar_grupo_api_grupos__ident__copia_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoRegistro"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    previa_grupo_api_grupos_previa_post: {
        parameters: {
            query: {
                id?: number | null;
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Previa"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    saida_grupo_api_grupos__ident__saida_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saida"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_blocos_api_blocos_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    salvar_blocos_api_blocos_put: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocosTexto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocos"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    previa_blocos_api_blocos_previa_post: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocosTexto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Previa"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    consultar_blocos_api_blocos_irr_post: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocosIrrPedido"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocosTexto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_config_api_config_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_config_organizada_api_config_organizada_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    baixar_base_base_txt_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    politica_do_cliente_politica_cliente_pdf_get: {
        parameters: {
            query: {
                asn: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raiz__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
