/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plano": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ler Plano
         * @description A rede e as tabelas do plano que o formulario usa para se preencher.
         */
        get: operations["ler_plano_api_plano_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rede": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Gravar Rede
         * @description O AS da rede no topo do peers.yaml, pelas conferencias do
         *     _asn_do_formulario.
         */
        put: operations["gravar_rede_api_rede_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Peers */
        get: operations["listar_peers_api_peers_get"];
        put?: never;
        /** Criar Peer */
        post: operations["criar_peer_api_peers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/novo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Novo Peer */
        get: operations["novo_peer_api_peers_novo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{ident}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Peer */
        get: operations["ler_peer_api_peers__ident__get"];
        /**
         * Atualizar Peer
         * @description Atualiza o registro do ID da URL.
         *
         *     O ID do corpo e editavel: se o operador o trocou, o registro da URL passa
         *     ao ID novo, e o validar recusa o que ja for de outro peer ou grupo.
         */
        put: operations["atualizar_peer_api_peers__ident__put"];
        post?: never;
        /** Excluir Peer */
        delete: operations["excluir_peer_api_peers__ident__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{ident}/copia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copiar Peer
         * @description O peer inteiro com o proximo ID livre, para abrir como peer novo.
         *
         *     Nao grava nada. O salvar recusa o que a copia repetir (token, IP remoto,
         *     prefixo de downstream) e aponta o campo, e o operador corrige ali.
         */
        get: operations["copiar_peer_api_peers__ident__copia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previa Peer
         * @description Valida e monta os blocos do formulario sem gravar nada.
         *
         *     O `id` e o do registro que a tela esta editando, e falta no peer novo. O
         *     erro de validacao volta em 200 e sem bloco. A remocao fica de fora: ela
         *     desfaz o que esta no equipamento, e o que esta no equipamento e o registro
         *     salvo, que o GET /api/peers/{ident}/saida devolve.
         */
        post: operations["previa_peer_api_peers_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers/{ident}/saida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saida Peer */
        get: operations["saida_peer_api_peers__ident__saida_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/irr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar Irr
         * @description Os prefixos do ASN no IRR, pelo bgpq4, sem gravar nada.
         *
         *     A consulta precisa so do ASN e do apelido: o resultado vai para os campos
         *     de prefixo da tela, que o operador ainda edita antes de salvar.
         */
        post: operations["consultar_irr_api_irr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Grupos */
        get: operations["listar_grupos_api_grupos_get"];
        put?: never;
        /** Criar Grupo */
        post: operations["criar_grupo_api_grupos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/novo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Novo Grupo */
        get: operations["novo_grupo_api_grupos_novo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/{ident}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Grupo */
        get: operations["ler_grupo_api_grupos__ident__get"];
        /** Atualizar Grupo */
        put: operations["atualizar_grupo_api_grupos__ident__put"];
        post?: never;
        /** Excluir Grupo */
        delete: operations["excluir_grupo_api_grupos__ident__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/{ident}/copia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copiar Grupo
         * @description O grupo inteiro com o proximo ID livre. O nome repetido e o que o
         *     salvar recusa. A copia nasce sem membro: os peers seguem no original.
         */
        get: operations["copiar_grupo_api_grupos__ident__copia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previa Grupo
         * @description A previa do grupo, com o mesmo contrato da do peer.
         */
        post: operations["previa_grupo_api_grupos_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos/{ident}/saida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saida Grupo */
        get: operations["saida_grupo_api_grupos__ident__saida_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Blocos */
        get: operations["ler_blocos_api_blocos_get"];
        /** Salvar Blocos */
        put: operations["salvar_blocos_api_blocos_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocos/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previa Blocos
         * @description O bloco de originacao que o salvar escreveria, sem gravar nada.
         */
        post: operations["previa_blocos_api_blocos_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocos/irr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar Blocos
         * @description Consulta o IRR do AS da rede e mescla com o texto recebido.
         *
         *     A base da mesclagem e o texto que veio, e nao o arquivo: o operador pode
         *     ter mexido numa linha antes de consultar. O prefixo torto e recusado antes
         *     da consulta, nomeado no campo dele. Nada e gravado.
         */
        post: operations["consultar_blocos_api_blocos_irr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/base.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Baixar Base */
        get: operations["baixar_base_base_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raiz
         * @description A raiz leva para a lista da SPA.
         *
         *     O 307 e temporario de proposito: um 308 ficaria no cache do navegador do
         *     operador, e voltar atras viraria limpeza de cache. Quem segue o redirect
         *     sem pensar e o HEALTHCHECK do Dockerfile, que bate em / desde antes deste
         *     corte e continua lendo 200 no fim da corrente (o /peers servido pelo build).
         */
        get: operations["raiz__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Aviso */
        Aviso: {
            /** Campo */
            campo: string;
            /** Mensagem */
            mensagem: string;
        };
        /** Blocos */
        Blocos: {
            texto: components["schemas"]["BlocosTexto"];
            /** Originacao */
            originacao?: string | null;
            /** Remover */
            remover?: string | null;
        };
        /** BlocosIrrPedido */
        BlocosIrrPedido: {
            /**
             * V4
             * @default
             */
            v4: string;
            /**
             * V6
             * @default
             */
            v6: string;
            /**
             * Forcar
             * @default false
             */
            forcar: boolean;
        };
        /**
         * BlocosTexto
         * @description O texto dos dois editores, no formato da textarea de hoje.
         *
         *     Uma linha por prefixo: o CIDR e depois as communities. Linha comecada por
         *     `!-` e prefixo fora de servico, e o `!-` no fim da linha e a marca do que
         *     sumiu da consulta ao IRR, que o salvar ignora.
         */
        BlocosTexto: {
            /**
             * V4
             * @default
             */
            v4: string;
            /**
             * V6
             * @default
             */
            v6: string;
        };
        /**
         * ErroResposta
         * @description O corpo de toda recusa da API: um erro por campo e os avisos.
         */
        ErroResposta: {
            /** Erros */
            erros: {
                [key: string]: string;
            };
            /**
             * Avisos
             * @default []
             */
            avisos: components["schemas"]["Aviso"][];
        };
        /** GrupoForm */
        GrupoForm: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Nome
             * @default
             */
            nome: string;
            /**
             * Tipo
             * @default parceiro
             */
            tipo: string;
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Classe
             * @default
             */
            classe: string;
            /**
             * Lp Base
             * @default
             */
            lp_base: string;
            /**
             * Origem
             * @default
             */
            origem: string;
            /**
             * Pop
             * @default
             */
            pop: string;
            /**
             * Aprendizado
             * @default
             */
            aprendizado: string;
            /**
             * Aprendizado Ix
             * @default
             */
            aprendizado_ix: string;
            /**
             * Ix Id
             * @default
             */
            ix_id: string;
            /**
             * Prepend Base
             * @default
             */
            prepend_base: string;
            /**
             * Timer Keepalive
             * @default
             */
            timer_keepalive: string;
            /**
             * Timer Hold
             * @default
             */
            timer_hold: string;
            /**
             * Bfd
             * @default true
             */
            bfd: boolean;
            /**
             * Graceful Restart
             * @default true
             */
            graceful_restart: boolean;
            /**
             * Default Route
             * @default false
             */
            default_route: boolean;
            /**
             * Bh Upstream
             * @default
             */
            bh_upstream: string;
            /**
             * Prefixos V4
             * @default []
             */
            prefixos_v4: string[];
            /**
             * Prefixos V6
             * @default []
             */
            prefixos_v6: string[];
            /**
             * Te Prefixos V4
             * @default []
             */
            te_prefixos_v4: string[];
            /**
             * Te Prefixos V6
             * @default []
             */
            te_prefixos_v6: string[];
            /**
             * Ap Block
             * @default []
             */
            ap_block: string[];
            /**
             * Ap Te
             * @default []
             */
            ap_te: string[];
            /**
             * Ap Allowed
             * @default []
             */
            ap_allowed: string[];
            /**
             * Ap Prefer
             * @default []
             */
            ap_prefer: string[];
            /**
             * Communities
             * @default []
             */
            communities: string[];
            /**
             * Large Communities
             * @default []
             */
            large_communities: string[];
        };
        /** GrupoRegistro */
        GrupoRegistro: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            formulario: components["schemas"]["GrupoForm"];
            /** Membros */
            membros: components["schemas"]["Membro"][];
        };
        /** GrupoResumo */
        GrupoResumo: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            /** Tipo */
            tipo: string;
            /** Membros */
            membros: number;
        };
        /** GrupoSalvo */
        GrupoSalvo: {
            registro: components["schemas"]["GrupoRegistro"];
            /** Arquivo */
            arquivo: string;
        };
        /** IrrPedido */
        IrrPedido: {
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Apelido
             * @default
             */
            apelido: string;
            /**
             * Forcar
             * @default false
             */
            forcar: boolean;
        };
        /** Membro */
        Membro: {
            /** Id */
            id: number;
            /** Token */
            token: string;
        };
        /**
         * Padroes
         * @description O _padroes() do formulario.py: o que a cascata de defaults le.
         */
        Padroes: {
            /** Tipos */
            tipos: {
                [key: string]: components["schemas"]["TabelaTipo"];
            };
            /** Origem Tipo */
            origem_tipo: {
                [key: string]: number;
            };
            /** Origem Classe */
            origem_classe: {
                [key: string]: number;
            };
            /** Downstream */
            downstream: string[];
            /** Origens Por Tipo */
            origens_por_tipo: {
                [key: string]: number[];
            };
            /** Origem Nome */
            origem_nome: {
                [key: string]: string;
            };
        };
        /** PeerForm */
        PeerForm: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Apelido
             * @default
             */
            apelido: string;
            /**
             * Nome
             * @default
             */
            nome: string;
            /**
             * Tipo
             * @default cliente
             */
            tipo: string;
            /**
             * Grupo Id
             * @default
             */
            grupo_id: string;
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Descricao
             * @default
             */
            descricao: string;
            /**
             * Classe
             * @default
             */
            classe: string;
            /**
             * Lp Base
             * @default
             */
            lp_base: string;
            /**
             * Origem
             * @default
             */
            origem: string;
            /**
             * Pop
             * @default
             */
            pop: string;
            /**
             * Aprendizado
             * @default
             */
            aprendizado: string;
            /**
             * Ix Id
             * @default
             */
            ix_id: string;
            /**
             * Route Limit
             * @default
             */
            route_limit: string;
            /**
             * Prepend Base
             * @default
             */
            prepend_base: string;
            /**
             * Timer Keepalive
             * @default
             */
            timer_keepalive: string;
            /**
             * Timer Hold
             * @default
             */
            timer_hold: string;
            /**
             * Bfd
             * @default true
             */
            bfd: boolean;
            /**
             * Graceful Restart
             * @default true
             */
            graceful_restart: boolean;
            /**
             * Default Route
             * @default false
             */
            default_route: boolean;
            /**
             * Bh Upstream
             * @default
             */
            bh_upstream: string;
            /**
             * Prefixos V4
             * @default []
             */
            prefixos_v4: string[];
            /**
             * Prefixos V6
             * @default []
             */
            prefixos_v6: string[];
            /**
             * Te Prefixos V4
             * @default []
             */
            te_prefixos_v4: string[];
            /**
             * Te Prefixos V6
             * @default []
             */
            te_prefixos_v6: string[];
            /**
             * Ap Block
             * @default []
             */
            ap_block: string[];
            /**
             * Ap Te
             * @default []
             */
            ap_te: string[];
            /**
             * Ap Allowed
             * @default []
             */
            ap_allowed: string[];
            /**
             * Ap Prefer
             * @default []
             */
            ap_prefer: string[];
            /**
             * Communities
             * @default []
             */
            communities: string[];
            /**
             * Large Communities
             * @default []
             */
            large_communities: string[];
            /**
             * Sessao V4 Local
             * @default
             */
            sessao_v4_local: string;
            /**
             * Sessao V4 Remoto
             * @default
             */
            sessao_v4_remoto: string;
            /**
             * Sessao V6 Local
             * @default
             */
            sessao_v6_local: string;
            /**
             * Sessao V6 Remoto
             * @default
             */
            sessao_v6_remoto: string;
        };
        /** PeerRegistro */
        PeerRegistro: {
            /** Id */
            id: number;
            /** Token */
            token: string;
            formulario: components["schemas"]["PeerForm"];
        };
        /**
         * PeerResumo
         * @description Uma linha da barra lateral e da paleta de comandos.
         */
        PeerResumo: {
            /** Id */
            id: number;
            /** Token */
            token: string;
            /** Tipo */
            tipo: string;
            /** Asn */
            asn: number;
            /** Apelido */
            apelido: string;
            /** Nome */
            nome: string;
            /** Grupo Id */
            grupo_id: number | null;
        };
        /** PeerSalvo */
        PeerSalvo: {
            registro: components["schemas"]["PeerRegistro"];
            /** Arquivo */
            arquivo: string;
            /**
             * Avisos
             * @default []
             */
            avisos: components["schemas"]["Aviso"][];
        };
        /** Plano */
        Plano: {
            rede: components["schemas"]["RedeAtual"];
            padroes: components["schemas"]["Padroes"];
            /** Tipos */
            tipos: string[];
            /** Tipos Com Criar Lista */
            tipos_com_criar_lista: string[];
            /** Classes Cliente */
            classes_cliente: string[];
            /** Lp Base */
            lp_base: {
                [key: string]: number;
            };
            /** Route Limit */
            route_limit: {
                [key: string]: number;
            };
            /** Route Limit Exemplo */
            route_limit_exemplo: {
                [key: string]: number;
            };
            /** Prepend Max */
            prepend_max: number;
            /** Prepend Implementado */
            prepend_implementado: number;
            /** Pop Min */
            pop_min: number;
            /** Pop Max */
            pop_max: number;
            /** Aprendizado Min */
            aprendizado_min: number;
            /** Aprendizado Max */
            aprendizado_max: number;
            /** Pop Usados */
            pop_usados: number[];
            /** Aprendizado Usados */
            aprendizado_usados: number[];
            /** Campos Por Tipo */
            campos_por_tipo: {
                [key: string]: string[];
            };
            /** Campos Por Tipo Grupo */
            campos_por_tipo_grupo: {
                [key: string]: string[];
            };
        };
        /** Prefixos */
        Prefixos: {
            /** V4 */
            v4: string[];
            /** V6 */
            v6: string[];
        };
        /**
         * Previa
         * @description O que o salvar escreveria, sem gravar nada.
         *
         *     Com erro de validacao, `erros` vem cheio e os blocos vem nulos: a tela nao
         *     pode ter o que copiar de um registro que o salvar recusaria. `salvo` e o
         *     arquivo atual em out/, para o diff, ou nulo quando nao ha.
         */
        Previa: {
            /**
             * Erros
             * @default {}
             */
            erros: {
                [key: string]: string;
            };
            /**
             * Avisos
             * @default []
             */
            avisos: components["schemas"]["Aviso"][];
            /** Bloco */
            bloco?: string | null;
            /** Criar Lista */
            criar_lista?: string | null;
            /** Arquivo */
            arquivo?: string | null;
            /** Salvo */
            salvo?: string | null;
        };
        /** RedeAtual */
        RedeAtual: {
            /** Asn */
            asn: string;
            /** Politica */
            politica: string;
        };
        /** RedeForm */
        RedeForm: {
            /**
             * Asn
             * @default
             */
            asn: string;
            /**
             * Politica
             * @default
             */
            politica: string;
        };
        /**
         * Saida
         * @description Os blocos do registro salvo, que e o que esta no equipamento.
         */
        Saida: {
            /** Bloco */
            bloco: string;
            /** Remover */
            remover?: string | null;
            /** Criar Lista */
            criar_lista?: string | null;
            /** Arquivo */
            arquivo: string;
        };
        /** TabelaTipo */
        TabelaTipo: {
            /** Lp Base */
            lp_base: number | null;
            /** Route Limit */
            route_limit: number | null;
            /** Timer Keepalive */
            timer_keepalive: number | null;
            /** Timer Hold */
            timer_hold: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ler_plano_api_plano_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plano"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    gravar_rede_api_rede_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeAtual"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    listar_peers_api_peers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerResumo"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    criar_peer_api_peers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerSalvo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    novo_peer_api_peers_novo_get: {
        parameters: {
            query?: {
                tipo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRegistro"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_peer_api_peers__ident__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRegistro"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    atualizar_peer_api_peers__ident__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerSalvo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    excluir_peer_api_peers__ident__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    copiar_peer_api_peers__ident__copia_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerRegistro"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    previa_peer_api_peers_previa_post: {
        parameters: {
            query?: {
                id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Previa"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    saida_peer_api_peers__ident__saida_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    consultar_irr_api_irr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IrrPedido"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prefixos"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    listar_grupos_api_grupos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoResumo"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    criar_grupo_api_grupos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoSalvo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    novo_grupo_api_grupos_novo_get: {
        parameters: {
            query?: {
                tipo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoRegistro"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_grupo_api_grupos__ident__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoRegistro"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    atualizar_grupo_api_grupos__ident__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoSalvo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    excluir_grupo_api_grupos__ident__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    copiar_grupo_api_grupos__ident__copia_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoRegistro"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    previa_grupo_api_grupos_previa_post: {
        parameters: {
            query?: {
                id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Previa"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    saida_grupo_api_grupos__ident__saida_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ident: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    ler_blocos_api_blocos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocos"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    salvar_blocos_api_blocos_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocosTexto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocos"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    previa_blocos_api_blocos_previa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocosTexto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Previa"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    consultar_blocos_api_blocos_irr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocosIrrPedido"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocosTexto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroResposta"];
                };
            };
        };
    };
    baixar_base_base_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    raiz__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
